var edad = 27;
edad += 1;
console.log(`${edad}`);
var peso = 75;
peso -= 1;
console.log(peso);
var precioVino = 200.3;
var total = Math.round(precioVino * 100 * 3) / 100;
console.log(total.toFixed(2));
var total2 = parseFloat(total);
